---
- name: Generate SSH keys
  shell: ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N ""
  args:
    creates: /root/.ssh/id_rsa.pub  # This argument ensures the command is only executed if the public key doesn't exis

- name: Fetch the generated public keys
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: /tmp/id_rsa.pub
    flat: yes
  throttle: 1     # To avoid the checksum failed error (otherwise, serial: 1 -> not ideal)


- name: Ensure the .ssh directory exists
  file:
    path: /root/.ssh
    state: directory
    mode: '0700'
    owner: root
  when: ansible_hostname != "LB"

- name: Add LB's public key to authorized_keys on web1, web2 and web3
  lineinfile:
    path: /root/.ssh/authorized_keys
    line: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
    create: yes
    mode: '0600'
    owner: root
  when: ansible_hostname != "LB"
